# This is a basic workflow to help you get started with Actions

name: Keep Expense Tracker API Azure App Service Alive

# Controls when the workflow will run
on:
  # Triggers the workflow on schedule events but only for the "main" branch
  schedule:
    - cron: '15 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ping"
  ping:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a set of commands using the runners shell
      - name: Ping API Health
        run: |
          curl --fail https://expense-tracker-api-286995024.azurewebsites.net/actuator/health \
          || echo "Azure App ping failed"
