# This is a basic workflow to help you get started with Actions

name: Keep Redis Cloud database-MDVHGNP8 Alive

# Controls when the workflow will run
on:
  # Triggers the workflow on schedule event
  schedule:
    - cron: '0 6 */7 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "keep-redis-warm"
  keep-redis-warm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell for login
      - name: Login
        run: |
          response=$(curl -s -X POST https://expense-tracker-api-286995024.azurewebsites.net/login \
            -H "Content-Type: application/json" \
            -d '{"email":"jane@doe.com","password":"password123"}')

          token=$(echo $response | jq -r '."access-token"')

          if [ "$token" = "null" ] || [ -z "$token" ]; then
            echo "Login failed or token not found"
            exit 1
          fi

          echo "::add-mask::$token"
          echo "token=$token" >> $GITHUB_OUTPUT

      # Runs a set of commands using the runners shell
      - name: Get Paginated Expense List
        run: |
          curl -X GET "https://expense-tracker-api-286995024.azurewebsites.net/expenses?page=0&size=10" \
            -H "Authorization: Bearer ${{ steps.login.outputs.token }}" \
            || echo "Redis ping failed"
